### ISSUE TITLE
First steps towards the reduction of long2pos

### ISSUE THREAD

**Issue by MosfireDRP** [Keck-DataReductionPipelines/MosfireDRP#12]
Dear colleagues

I have a first version of the long2pos reduction. I managed to finish a reduction and the reduced spectrum is attached. The code lives in a special and separate branch called Longslit.

Some notes:

- I modified the code that reads the CSU extension to reject entire any information related to posB. It was creating a fake slit where we have no data, and with large lines
- I fixed a possible problem with CSU, which was assigning the wrong slits numbers to specific science names. See https://github.com/Mosfire-DataReductionPipeline/MosfireDRP/issues/11
- there is a new find_long2pos_edges routine in Flats.py to simplify the detection of the edges when only two slits are significant
- a fixed an error in Wavelength.py. The code was trying to determine the delta lambda resolution of the wavelength solutions by looking at row 1024, in the assumption that the central row of the mosaic would contain data. This is not the case for the long2pos, as the wavelength calibration is only present in positions A and C. I replaced that assumption with a search algorithm.

The automatic procedure that creates the Offsets files doesn't work for long2pos. If an observer observes 3 standards throught the night, the result is a series of Offsets files with combined frames from the  3 standards, rather than for each standard. This is a common problem to the longslit reduction as well. Basically we need to decide how we want to produce the Offset files when the name of the mask is the same, but the target is different. For the moment, one has to manually edit the Offset files to remove the frames that don't belong to the target being reduced.

The procedure that determines the observing plan is also broken, because when we offset to the top left slit and we take the two frames (at offsets -7 and -21), we get two fits files where FRAMEID = A
So the plan is [['A']]. Manually specifying plan=[['A','B']] doesn't work, as there are no files where FRAMEID=B. For the time being, I have manually edited the file headers of the -21 position to be FRAMEID=B, and everything works. 

Still to be done: we only observe one frame per position, so I need to disable CRR completely. 

This is reduced and extracted file:

![image](https://cloud.githubusercontent.com/assets/9344283/6095244/658b5cd6-aef6-11e4-98c4-2d46a67446c8.png)

Please have a look at the code changes, and feel free to provide feedback on how to move forward. 
In particular, I think it's urgent to solve the problem of how to create appropriate directories/Offset files for long2pos observations where the maskname is the same. should we look at the target name?

**Comment by MosfireDRP** [comment]
I fixed a couple of problems. First of all, I am now generating separate Offset files for the different objects. I modified handle.py to do that.
Second, I solved the problem of both the -7 and -21 frames having FRAMEID="A". I added code that automatically modifies the FRAMEID to "B" for one of the files, only in the long2pos case.

Verified and it all works.

**Comment by csteidel** [comment]
Hi Luca,
    How do I go about getting a copy of the changed code to test it out?  I could not find it on the GitHub site- the latest update
seemed to be from a month ago… (sorry, I have no experience with github and find the interface kind of baffling). 

   Thanks,
     Chuck

**Comment by csteidel** [comment]
Hi Luca,
    I am trying to run through a long2pos reduction and am having a problem at the Background
stage with the plan=[] keyword.  In the dataset I am using, the image headers actually all have
“object” for the FRAMEID keyword. Perhaps this is because I use the long2pos_specphot mask
configuration and you software only dealt with the “long2pos” case?  In case you are unfamilar,
long2pos_specphot  leaves one bar open to 4” in the middle of each of the slits, and obtains
a spectrum in 3 positions, 7”,14”,21” where the central position gets all of the light, so that one
can measure the slit losses for the narrow slits.  Note that we use calibrations taken through 
the long2pos mask for calibrations— these are not currently associated (by mospy handle) with
long2pos_specphot observations, but it is easy enough to copy across the Ne.txt. Ar.txt, and
Flat.txt files from the long2pos directory created by handle).  

   It seems like a better general solution for identifying the “plan” might be to read the YOFFSET 
and XOFFSET keywords, which are always set properly. For example, the image at the “-21” offset
position in my dataset has FRAMEID=“object”, but has:

XOFFSET =               250.25 / dither pattern X offset
YOFFSET =                  -21 / dither pattern Y/Nod offset

The first tells us which slit is involved (left or right) and the second tells us what
the offset along the slit is.  

For calibration stars, I would have said that the most useful output would keep 
each observation of the star as a separate (i.e., not combined with other observations
on the same slit) background-subtracted 2d spectrum. The background subtraction
can be done in a pairwise fashion (any frame other than itself can be used for any
other frame in the sequence).

In any case, to make your version of the software work with long2pos_specphot, I 
guess I need to change FRAMEID by hand for each image (i.e., one A and one B
in your current implementation)?  I have included the driver script I am using 
(it is H band, and I am using Argon taken with long2pos for wavelength calibration 
because sky line method will fail for long2pos_specphot due to wide portion of the
slit). 

    Chuck
import os, time
import MOSFIRE

from MOSFIRE import Background, Combine, Detector, Flats, IO, Options, Rectify
from MOSFIRE import Wavelength, Longslit

import numpy as np, pylab as pl, pyfits as pf

np.seterr(all="ignore")

maskname = 'long2pos_specphot'
band = 'H'

flatops = Options.flat
waveops = Options.wavelength

# Note: for long2pos, the row position is ignored, and the middle point of the slit is used
longslit = {'yrange': [[1062,1188],[887,1010]], 'row_position': 0}

#obsfiles = ['Offset_21_HIP65210.txt', 'Offset_7_HIP65210.txt']
obsfiles = ['Offset_-7_HIP53735.txt', 'Offset_-21_HIP53735.txt']

#Flats.handle_flats('Flat.txt', maskname, band, flatops, longslit = longslit)

# SKY LINES
# Use sky lines for wavelength calibration
# Use either Sky lines or Neon lines.
#Wavelength.imcombine(obsfiles, maskname, band, waveops)
#Wavelength.fit_lambda_interactively(maskname, band, obsfiles, waveops, longslit=longslit)
#Wavelength.fit_lambda(maskname, band, obsfiles, obsfiles, waveops, longslit=longslit)
#Wavelength.apply_lambda_simple(maskname, band, obsfiles, waveops, longslit=longslit, smooth=True)

# NEON or ARGON
Wavelength.imcombine('Ar.txt', maskname, band, waveops)
Wavelength.fit_lambda_interactively(maskname, band, 'Ar.txt', waveops, longslit=longslit, argon=True,)
Wavelength.fit_lambda(maskname, band, 'Ar.txt', 'Ar.txt', waveops, longslit=longslit)
Wavelength.apply_lambda_simple(maskname, band, 'Ar.txt', waveops, longslit=longslit, smooth=True)


# Update the following line after the apply_lambda_simple step
Longslit.go(maskname, band, obsfiles ,
   'lambda_solution_wave_stack_H_m141123_0112-0112.fits',
    waveops, longslit)

Background.handle_background(obsfiles,
    'lambda_solution_wave_stack_H_m141123_0112-0112.fits',
    maskname, band, waveops, plan=[['A', 'B']])

redfiles = ["eps_" + file + ".fits" for file in obsfiles]
#update the "lambda_solution_wave_stack_K*.fits" file name
#  to the output file name from the apply_lambda process above.
# Update the name of the first file in the offset file (use the full path name.
#   e.g.    "/Users/user1/MOSFIRE/DRP_CODE/DATA/2014may08/m130114_0451.fits",

Rectify.handle_rectification(maskname, redfiles,
    "/Users/ccs/data/raw_data/2014nov23/m141123_0109.fits",
    band, 
    obsfiles,
    waveops)

**Comment by MosfireDRP** [comment]
> On Feb 19, 2015, at 7:13 AM, csteidel <notifications@github.com> wrote:
> 
> Hi Luca,
> I am trying to run through a long2pos reduction and am having a problem at the Background
> stage with the plan=[] keyword. In the dataset I am using, the image headers actually all have
> “object” for the FRAMEID keyword. Perhaps this is because I use the long2pos_specphot mask
> configuration and you software only dealt with the “long2pos” case? In case you are unfamilar,
> long2pos_specphot leaves one bar open to 4” in the middle of each of the slits, and obtains
> a spectrum in 3 positions, 7”,14”,21” where the central position gets all of the light, so that one
> can measure the slit losses for the narrow slits. Note that we use calibrations taken through 
> the long2pos mask for calibrations— these are not currently associated (by mospy handle) with
> long2pos_specphot observations, but it is easy enough to copy across the Ne.txt. Ar.txt, and
> Flat.txt files from the long2pos directory created by handle). 

Chuck

I didn’t know that the long2pos_specphot procedure produces “object” as the content of FRAMEID.

I think it’s safe to say that what I have developed so far does not work for the specphot variant of long2pos.

> 
> It seems like a better general solution for identifying the “plan” might be to read the YOFFSET 
> and XOFFSET keywords, which are always set properly. For example, the image at the “-21” offset
> position in my dataset has FRAMEID=“object”, but has:
> 
> XOFFSET = 250.25 / dither pattern X offset
> YOFFSET = -21 / dither pattern Y/Nod offset
> 
> The first tells us which slit is involved (left or right) and the second tells us what
> the offset along the slit is. 

INdeed, I will definitely look into it.


> 
> For calibration stars, I would have said that the most useful output would keep 
> each observation of the star as a separate (i.e., not combined with other observations
> on the same slit) background-subtracted 2d spectrum. The background subtraction
> can be done in a pairwise fashion (any frame other than itself can be used for any
> other frame in the sequence).
> 
> In any case, to make your version of the software work with long2pos_specphot, I 
> guess I need to change FRAMEID by hand for each image (i.e., one A and one B
> in your current implementation)? I have included the driver script I am using 
> (it is H band, and I am using Argon taken with long2pos for wavelength calibration 
> because sky line method will fail for long2pos_specphot due to wide portion of the
> slit). 


This is probably true, but I wouldn’t want you to spend too much time trying this out. I am happy to download your data set and perfect the procedure so that it handles your data directly.

Would you be able to make them available to me in a ftp site of some sort?

Cheers
Luca

**Comment by lucarizzi** [comment]
I have pushed a couple of commits to deal with the long2pos_specphot reduction. I have been able to reduce both the narrow and wide slits with no problems, but I haven't had time to document the procedure in the manual yet, and to test it extensively. There is a new driver file specific for this kind of observations, but I plan to merge it with the one for the standard long2pos after testing.

**Comment by MosfireDRP** [comment]
implemented
