### ISSUE TITLE
Next pipeline release for mid summer 2015

### ISSUE THREAD

**Issue by lucarizzi** [Keck-DataReductionPipelines/MosfireDRP#22]
We would like to start discussing what to include in the next pipeline release.

There are issues with the wavelength solutions that we would like to resolve, mostly related to the combined use of arcs and sky lines.
We would like to introduce the long2pos and longslit reductions
We would also like to use the new packaging system that Tuan is working on.

Any other idea/suggestions?

**Comment by csteidel** [comment]
> There are issues with the wavelength solutions that we would like to resolve, mostly related to the combined use of arcs and sky lines.

Can you say more about the item above?  
> We would like to introduce the long2pos and longslit reductions
> 
Would this include the “long2pos_specphot” configuration? I think the only real difference
needed for long2pos_specphot is that the wavelength solutions must come from arc
lamps taken with long2pos configuration (so that good wavelength solutions are obtained
in regions with wider slits).  
> We would also like to use the new packaging system that Tuan is working on.
> 
> 
Can you say more about the above item? 
> Any other idea/suggestions?
> 
> 
Here are a few things that I think would make the DRP easier/more convenient to use:

1.  modify “mospy handle” so that it produces a default driver script in each mask directory with
the relevant file names properly inserted, with a name like “<maskname>.driver.py”  or something
similar.  Since the names of the wavelength solution files and a file name with proper header
information can be anticipated from the “Offset*.txt” files, it would allow the whole script to
be executed in one go rather than requiring hand editing and executing the script multiple times
with steps commented out. 

2.  make a section of the documentation that suggests the best approaches for wavelength
calibrations in each band (e.g., for K band, Ne arcs to supplement sky lines).  

3. make it possible to use a combination of Neon and Argon arcs to calibrate short integrations
where the sky lines are not well-exposed.  For the long2pos_specphot observations, sky lines
will not work for wavelength solutions because of the regions of the slits with 4” width.  This may
involve making good “combined arc” linelists which removes lines that are blends of Ne and Ar so
that combined Ne+Ar arcs can be used for calibration purposes.


Suggestions for improvement to the algorithms within the code:

1.  The current algorithm for combining frames prior to differencing is sub-optimal in
cases having a small number of frames or when the sky continuum is fluctuating
due to passing clouds (or near twilight).  In the former case, it is difficult to identify
cosmic ray events without throwing away a significant fraction of the data; in the latter
case, CRs will remain unidentified because of large rms among frames taken at a given
position (the CR idenitification relies on what amounts to sigma clipping, and if sigma 
is large due to gross background fluctuations, then CRs that otherwise would have
been identified do not exceed the threshold and thus remain present in the reduced data. 
I have some ideas about how to improve both of these cases- maybe we can discuss
while I am out there (tomorrow, May 15, through Monday night, May 18).  

2. There is a parameter that needs adjustment in the edge tracing part of processing flat
fields- I have been finding that edge tracing fails on approximately one slit per mask, I
suspect because the threshold for edge finding is set to a number of ADU that is too large. 

3. The response function (sensitivity vs. wavelength) varies depending on slit position in
the field near the edges of the order sorting filter bandpasses (because the filters are
interference filters, the exact wavelength of the cut-on and cut-off depends on angle of
incidence). These variations are 
not adequately captured using calibration star observations since they do not sample
the same range of field positions as slits on masks.  This could be corrected in a differential
way using a different means of normalizing the flat fields, or by producing a response correction
for each slit obtained by examining the differential behavior of its (wavelength-calibrated and
rectified) 1-d collapsed flat field spectra relative to some fiducial slit.

**Comment by lucarizzi** [comment]
There are issues with the wavelength solutions that we would like to resolve, mostly related to the combined use of arcs and sky lines.
Can you say more about the item above?

You said it already! The issues that you mention in your suggestion number 3 regarding the combination of Ne/Ar is exactly what we had in mind.

 We would also like to use the new packaging system that Tuan is working on.

Can you say more about the above item?

Most of the python packages are distributed in a uniform way using the built-in packaging system that python offers. If we do this, the installation of the pipeline would be as easy as saying "pip install mosfiredrp" or something like that.
See #18 

Chuck, your additional suggestions are very interesting and definitely should be added. I will be your support astronomer during your upcoming LRIS run. Maybe we can talk about them?

**Comment by monodera** [comment]
Hi Luca,

I'm not sure if here is the right place to mention it, but I have a suggestion for implementation of the DRP. 

In `Wavelength.py`, the minimum required number of lines for wavelength calibration is hard-coded as 5. I had a K-band mask in which one of slits is placed at large X. In the calibration with sky+arc, it cannot handle this slit and it crashed with error at the arc stage because number of available arc lines is less than 5. In the end, this wavelength can be well calibrated only with sky, but the rest of the slits needs to be calibrated with arc+sky.  I think it would be nice if you can implement a way to treat this kind of situations properly for the next release.  

What I did to run the pipeline is the following. (maybe it's not proper way)

```diff
--- Options.py.org	2015-02-18 14:07:26.000000000 +0100
+++ Options.py	2015-02-26 14:35:47.000000000 +0100
@@ -24,5 +24,5 @@
         "version": 2,
         "fractional-wavelength-search": 0.99935, # used in determining oned wavelength solutions
         "chebyshev-degree": 5, # polynomial order for fitting wavelengths
+        "chebyshev-degree-min": 2 # minimum allowed polynomial order for fitting wavelengths
 }

--- Wavelength.py.org	2015-02-19 10:37:24.000000000 +0100
+++ Wavelength.py	2015-02-27 21:38:07.000000000 +0100
@@ -1494,8 +1495,15 @@
     badfit = np.zeros(options["chebyshev-degree"]+1)
     baddelt = np.ones(L) * 9999.0

-    if L < 6:
+    cv_degree_org = options["chebyshev-degree"]
+    is_cv_degree_temp = False
+
+    if L < options["chebyshev-degree-min"]+1:
         return [baddelt, badfit, lines[ok]]
+    elif L < options["chebyshev-degree"]+1:
+        is_cv_degree_temp = True
+        options["chebyshev-degree"] = L-1
+        print("Temporarily change Chebyshev degree from %i to %i" % (cv_degree_org, L-1))

     if np.median(lines) < 1000:
         raise Exception("Units fed to this function are likely in micron but "
@@ -1504,6 +1512,10 @@
     cfit = CV.chebfit(xs[ok], lines[ok], options["chebyshev-degree"])
     delt = CV.chebval(xs[ok], cfit) - lines[ok]

+    if is_cv_degree_temp==True:
+        print("Chebyshev degree back to %i" % (cv_degree_org))
+        options["chebyshev-degree"] = cv_degree_org
+
     if cfit is None:
         return [baddelt, badfit, lines[ok]]
```

Best, 
Masato

**Comment by lucarizzi** [comment]
Done
