### ISSUE TITLE
Poor sky subtraction (possibly due to the star being close to the edge of the slit)

### ISSUE THREAD

**Issue by lucarizzi** [Keck-DataReductionPipelines/MosfireDRP#30]
I have two observations of the same mask taken in Dec 27, 2012 and Jan 13, 2013. Exactly same mask, same band, same exposure time.

The difference is due to a bug that at the time affected the ABBA script, the stars are well centered (spatially) on the slit in Dec 27, but they are offset towards the lower edge of the slit in Jan 13.

A cut-out of the final reduced Dec 27 spectrum is here:

![image](https://cloud.githubusercontent.com/assets/524957/8759168/4a13b892-2c8a-11e5-97a6-fc97390b90ca.png)

The one from Jan 13 is here:

![image](https://cloud.githubusercontent.com/assets/524957/8759192/984ffe8a-2c8a-11e5-84bb-5b8e21da1954.png)

The sky subtraction is quite bad.

It seems that the model sky being calculated by Background.py is affected by the presence of a star close to the edge, or at least that is a possibility.

As a side note, and to make sure that this is not a problem introduced by changes to the pipeline introduced recently, I have re-reduced the dataset with the pre-WMKO version of the pipeline, and got exactly the same results.

The Jan 13 star positions are shifted down by 15 pixels with respect to the positions in Dec 27. In fact, the shift is enough to have cause some of the stars to fall off the edge of the slit.

For those interested in why this happened, during the January observations the ABBA script did not restore the central position after the cycle, so that the actual sequence ended up being:

J  band

A B B A

H band

A' B' B' A'

where A ' = A + 15 pixels, because at the end of the J sequence we did not return to zero, but stayed at A

Luca

**Comment by nickkonidaris** [comment]
Can you put the data somewhere that I can access it please?

On Friday, July 17, 2015, lucarizzi <notifications@github.com> wrote:

> I have two observations of the same mask taken in Dec 27, 2012 and Jan 13,
> 2013. Exactly same mask, same band, same exposure time.
>
> The difference is due to a bug that at the time affected the ABBA script,
> the stars are well centered (spatially) on the slit in Dec 27, but they are
> offset towards the lower edge of the slit in Jan 13.
>
> A cut-out of the final reduced Dec 27 spectrum is here:
>
> [image: image]
> <https://cloud.githubusercontent.com/assets/524957/8759168/4a13b892-2c8a-11e5-97a6-fc97390b90ca.png>
>
> The one from Jan 13 is here:
>
> [image: image]
> <https://cloud.githubusercontent.com/assets/524957/8759192/984ffe8a-2c8a-11e5-84bb-5b8e21da1954.png>
>
> The sky subtraction is quite bad.
>
> It seems that the model sky being calculated by Background.py is affected
> by the presence of a star close to the edge, or at least that is a
> possibility.
>
> As a side note, and to make sure that this is not a problem introduced by
> changes to the pipeline introduced recently, I have re-reduced the dataset
> with the pre-WMKO version of the pipeline, and got exactly the same results.
>
> The Jan 13 star positions are shifted down by 15 pixels with respect to
> the positions in Dec 27. In fact, the shift is enough to have cause some of
> the stars to fall off the edge of the slit.
>
> For those interested in why this happened, during the January observations
> the ABBA script did not restore the central position after the cycle, so
> that the actual sequence ended up being:
>
> J band
>
> A B B A
>
> H band
>
> A' B' B' A'
>
> where A ' = A + 15 pixels, because at the end of the J sequence we did not
> return to zero, but stayed at A
>
> Luca
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Keck-DataReductionPipelines/MosfireDRP/issues/30>.
>


-- 
Sent from Gmail Mobile

**Comment by MosfireDRP** [comment]
Sure!

it is now on our ftp server

ftp ftp.keck.hawaii.edu <http://ftp.keck.hawaii.edu/>
anonymous

cd outgoing/lrizzi

I have included the raw data, and the reduced data I have obtained.

This is the driver file for the pre-WMKO version of the pipeline.

I can add the driver also for the current version if needed, depending on which version you would like to look at.

import os, time, logging
import MOSFIRE
from MOSFIRE import Background, Combine, Detector, Flats, IO, Options, Rectify, Wavelength
from MOSFIRE.MosfireDrpLog import info, debug, warning, error
#logger = logging.getLogger(__name__)
import numpy as np, pylab as pl, pyfits as pf
np.seterr(all='ignore')
flatops = Options.flat
waveops = Options.wavelength

#Driver file automatically generated on Tue Jul 14 17:13:09 2015
#For questions and comments, email mosfiredrp@gmail.com, submit a ticket on the ticketing system, or contact Luca Rizzi @ WMKO

maskname = 'leoImask01'
band = 'H'

#Set bypass to True to autofit wavelenth solution instead of manually fitting.
bypassflag=False
obsfiles=['Offset_1.25.txt','Offset_-1.25.txt']

Flats.handle_flats('Flat.txt', maskname, band, flatops)

Wavelength.imcombine(obsfiles, maskname, band, waveops)
Wavelength.fit_lambda_interactively(maskname, band, obsfiles,waveops, bypass=bypassflag)
Wavelength.fit_lambda(maskname, band, obsfiles, obsfiles,waveops)
Wavelength.apply_lambda_simple(maskname, band, obsfiles, waveops)


Wavelength_file = 'lambda_solution_wave_stack_H_m130114_0510-0512.fits'

Background.handle_background(obsfiles,Wavelength_file,maskname,band,waveops)

redfiles = ["eps_" + file + ".fits" for file in obsfiles]
Rectify.handle_rectification(maskname, redfiles,Wavelength_file,band,"/Volumes/PromiseRAID/MOSFIRE/DRP_CODE/DATA/2013jan13/m130114_0511.fits",waveops)

**Comment by lucarizzi** [comment]
No further work on this issue. Closing.
