### ISSUE TITLE
Extraneous DATASEC keyword in Nov 2014 data causes problems

### ISSUE THREAD

**Issue by lucarizzi** [Keck-DataReductionPipelines/MosfireDRP#32]
While reducing data taken in nov 30, 2014, I run into a strange problem.
The slits did not have the correct wavelength coverage: in J band, rather than going from 11533 to 13520, the range was 11533 to 14197.
Close inspection revealed that the actual pixel values of the frame from 13520 to 14197 (the extra part) were a copy of the initial part of the slit, from 11533 on, as if the fits writer had "wrapped around" and copied the initial part of the slit.

Digging deep, I discovered that the problem is the presence of the keyword DATASEC, set to [1:2048, 1:2048]. That keyword is not present in my other data taken at different dates.

For some strange reason, if the fits writer does not have enough data to fill up the required DATASEC, it wraps around and reuses the same data.

Anyhow, the fix is to delete this keyword when it is present. I did so in IO.py using these lines of code, and it all works now.

        datasec = ""
        try:
            datasec = header["DATASEC"]
            warning("%s contains a DATASEC keyword not compatible with the pipeline" % path)
            warning("The content of the keyword will be erased on the reduced data")
            del header["DATASEC"]
        except:
            pass

**Comment by csteidel** [comment]
Hi Luca,
   I have noticed this for the mosaic of all of the slits (I’ve only seen it in J band) but I had not noticed it on the reductions of individual slits.
It has been a continuous feature for quite a while of the J-band mosaics but since it did not seem to impact the individual slit reductions I never tried to find out the cause. That is great that you found it!

   Chuck
