### ISSUE TITLE
Background.imcombine logic on number of files

### ISSUE THREAD

**Issue by drhay53** [Keck-DataReductionPipelines/MosfireDRP#59]
The following logic appears in Background.imcombine lines 230-254:

``` python
if len(files) >=5:
    .....stuff....
elif len(files) >5:
   .... stuff that can't possibly ever be executed under this logic
```

The number of files on the first logic instance is different for new_from_chuck True and False (5 vs 9, line 230 vs line 290). I don't know if this is intentional, but obviously with the above logic the elif can never be executed.

**Comment by joshwalawender** [comment]
I'm closing this as the code chunk which could not be executed under this logic has now been removed for the 2016 release.  It was simply an alternative combine which rejected the min and max values instead of using sigma clipping.  This could be reproduced easily using `ccdproc.combine` with the appropriate arguments or by resurrecting this code chunk.
