### ISSUE TITLE
MOSFIRE FITS Files Fail to Open in Astropy v1.3

### ISSUE THREAD

**Issue by joshwalawender** [Keck-DataReductionPipelines/MosfireDRP#69]
This is an issue with astropy's changes to the way FITS files are opened in v1.3.  There may be a minor problem with the way MOSFIRE files are written (see discussion on astropy issue).

See issue #5807 in astropy: https://github.com/astropy/astropy/issues/5807

For now, astropy v1.3 is incompatible with MOSFIRE FITS files.

**Comment by joshwalawender** [comment]
According to the discussion in astropy: https://github.com/astropy/astropy/issues/5807
this will be fixed in astropy v1.3.1 by slightly relaxing the requirements when reading the FITS header.

__IMPORTANT__:  The MOSFIRE DRP (and all attempts to open a MOSFIRE file using astropy) __will FAIL__ if using astropy v1.3.  There is no graceful workaround at the moment, so please downgrade to astropy v1.2.1 if you want to use the MOSFIRE DRP prior to the release of astropy v1.3.1.

**Comment by dmkassis** [comment]
Let's fix this when MOSFIRE comes off sky.

Marc

On Feb 14, 2017, at 5:32 PM, Josh Walawender <notifications@github.com<mailto:notifications@github.com>> wrote:


According to the discussion in astropy: astropy/astropy#5807<https://github.com/astropy/astropy/issues/5807>
this will be fixed in astropy v1.3.1 by slightly relaxing the requirements when reading the FITS header.

IMPORTANT: The MOSFIRE DRP (and all attempts to open a MOSFIRE file using astropy) will FAIL if using astropy v1.3. There is no graceful workaround at the moment, so please downgrade to astropy v1.2.1 if you want to use the MOSFIRE DRP prior to the release of astropy v1.3.1.

**Comment by lucarizzi** [comment]
Excellent !

**Comment by joshwalawender** [comment]
Opening MOSFIRE FITS files works in recent versions of astropy (v1.3.1+).  I have not found a workaround for astropy v1.3.0, but am closing because the fix is to upgrade to a later version of astropy.

Keck is also going to modify the keywords written by MOSFIRE to comply with this technicality of the FITS specification for the future.
