### ISSUE TITLE
DRP Installation Specifics for Python Newbies / Wavelength calibration problem

### ISSUE THREAD

**Issue by caitlinmcasey** [Keck-DataReductionPipelines/MosfireDRP#72]
Hi folks -

Brief note about my earlier installation problem that might be of use to others experiencing installation issues (this is on Mac OS X Sierra). Good news is that anaconda saved me on the install issue; being relatively new to python it wasn’t obvious to me that the most recent version of numpy wouldn’t be installed with the "pip install numpy" command, and therefore astropy would be ‘broken.’  To install without an issue I first had to install anacdona, then edit the PYTHONPATH in my .bash_profile (or .profile) file to point first to the anaconda directories (site-packages) and then the system python directories (which was the default PYTHONPATH on my laptop).  Then I had to upgrade the numpy installation with "sudo pip install numpy --upgrade" (only works as superuser) and then "sudo pip install astropy -- upgrade".  Then I follow the steps of the DRP installation.

Perhaps if you want to avoid other users running into a similar problem you could make it clear on the install page that a certain version of numpy (>1.12) is needed to run astropy, and a certain version of astropy (>1.3.2) is needed for mospy to read fits files correctly.  I found this information by some googling, after I figured out that was the problem, but it would be really helpful to have some information on how to check the version on the install page for python newbies.

I’m running into a new issue with wavelength calibration now, however.  It’s vaguely reminiscent of this thread:
https://groups.google.com/forum/m/#!msg/mosfire-drp/q6hSOQuicYs/Hg3B1F8I0UsJ

but that thread doesn’t solve my problem.

I am attempting to run the step:
Wavelength.fit_lambda(maskname, band, 'Ne.txt', 'Ne.txt',waveops, wavenames2='Ar.txt')
and I get the following error message:

2017-05-15 19:34:32,299 -   Wavelength.          fit_lambda - INFO: gdn4] Writing to: lambda_coeffs_wave_stack_K_m170508_0125-0127.npy
2017-05-15 19:34:32,653 -   Wavelength.   fit_lambda_helper - INFO: * Fitting Slit gdl2995 from 1907 to 1942
2017-05-15 19:34:32,654 -   Wavelength.  fit_outwards_refit - INFO: Computing 0 spectrum at 1924
2017-05-15 19:34:32,654 -   Wavelength.   fit_lambda_helper - INFO: * Fitting Slit GN-z11 from 7 to 82
2017-05-15 19:34:32,654 -   Wavelength.   fit_lambda_helper - INFO: * Fitting Slit gdl3759 from 1818 to 1853
2017-05-15 19:34:32,655 -   Wavelength.   fit_lambda_helper - INFO: * Fitting Slit gdl3786 from 1730 to 1765
2017-05-15 19:34:32,655 -   Wavelength.  fit_outwards_refit - INFO: Computing 0 spectrum at 45
2017-05-15 19:34:32,656 -   Wavelength.  fit_outwards_refit - INFO: Computing 0 spectrum at 1747
2017-05-15 19:34:32,656 -   Wavelength.  fit_outwards_refit - INFO: Computing 0 spectrum at 1836
Traceback (most recent call last):
  File "Driver.py", line 40, in <module>
    Wavelength.fit_lambda(maskname, band, 'Ne.txt', 'Ne.txt',waveops, wavenames2='Ar.txt')
  File "/Users/cmc3283/anaconda/lib/python2.7/site-packages/MOSFIRE-1.0.dev0-py2.7.egg/MOSFIRE/Wavelength.py", line 365, in fit_lambda
    solutions = p.map(fit_lambda_helper, range(len(bs.ssl)))
  File "/Users/cmc3283/anaconda/lib/python2.7/multiprocessing/pool.py", line 252, in map
    return self.map_async(func, iterable, chunksize).get()
2017-05-15 19:34:32,660 -   Wavelength.   fit_lambda_helper - INFO: * Fitting Slit gdl3094 from 1554 to 1634
  File "/Users/cmc3283/anaconda/lib/python2.7/multiprocessing/pool.py", line 568, in get
    raise self._value
TypeError: slice indices must be integers or None or have an __index__ method
2017-05-15 19:34:32,661 -   Wavelength.  fit_outwards_refit - INFO: Computing 0 spectrum at 1592
2017-05-15 19:34:32,661 -   Wavelength.   fit_lambda_helper - INFO: * Fitting Slit gdl3587 from 1464 to 1498
2017-05-15 19:34:32,662 -   Wavelength.  fit_outwards_refit - INFO: Computing 0 spectrum at 1482

The lambda_coeffs… file is not created, and my impression is that the wavelength solution is just failing to fit across the whole slit, while the interactive portion ran smoothly.  I’ve tried to redo the wavelength solution to make sure I didn’t fail to fit any of the slits, but everything looked fine (all slits had good solutions in the interactive sky-based wavelength solution fit).  I don’t know if the issue was in trying to merge the wavelength solution from the sky with the arcs?

Is there supposed to be some useful output from the step before to tell whether that ran properly? 
Wavelength.apply_interactive(maskname, band, waveops, apply=obsfiles, to='Ar.txt', argon=True)

I get the lambda_center_coeffs_… files for both lamps, and that’s it.  It appeared to run without error.

Any ideas y’all might have as a fix would be very useful.

Best,
Caitlin

**Comment by csteidel** [comment]
Hi Caitlin,

   On the subject of the second issue, if you are reducing a K band spectrum, you should change the line


Wavelength.fit_lambda(maskname, band, 'Ne.txt', 'Ne.txt',waveops, wavenames2=‘Ar.txt')

to

Wavelength.fit_lambda(maskname, band, 'Ne.txt', 'Ne.txt',waveops)

i.e., remove the reference to Ar.txt altogether.  The Argon spectrum in K has
very weak lines and so the automatic wavelength solution often fails— in fact,
Argon contributes little  in the K band so that you are better off without it.

 Josh/Luca -- the default driver file for a K band reduction should be changed to remove
the “wavenames2=‘Ar.txt’” (I always have to remove it by hand). I thought we had
had fixed this issue before, but apparently not.

      Chuck


On May 16, 2017, at 2:06 PM, caitlinmcasey <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi folks -

Brief note about my earlier installation problem that might be of use to others experiencing installation issues (this is on Mac OS X Sierra). Good news is that anaconda saved me on the install issue; being relatively new to python it wasn’t obvious to me that the most recent version of numpy wouldn’t be installed with the "pip install numpy" command, and therefore astropy would be ‘broken.’ To install without an issue I first had to install anacdona, then edit the PYTHONPATH in my .bash_profile (or .profile) file to point first to the anaconda directories (site-packages) and then the system python directories (which was the default PYTHONPATH on my laptop). Then I had to upgrade the numpy installation with "sudo pip install numpy --upgrade" (only works as superuser) and then "sudo pip install astropy -- upgrade". Then I follow the steps of the DRP installation.

Perhaps if you want to avoid other users running into a similar problem you could make it clear on the install page that a certain version of numpy (>1.12) is needed to run astropy, and a certain version of astropy (>1.3.2) is needed for mospy to read fits files correctly. I found this information by some googling, after I figured out that was the problem, but it would be really helpful to have some information on how to check the version on the install page for python newbies.

I’m running into a new issue with wavelength calibration now, however. It’s vaguely reminiscent of this thread:
https://groups.google.com/forum/m/#!msg/mosfire-drp/q6hSOQuicYs/Hg3B1F8I0UsJ

but that thread doesn’t solve my problem.

I am attempting to run the step:
Wavelength.fit_lambda(maskname, band, 'Ne.txt', 'Ne.txt',waveops, wavenames2='Ar.txt')
and I get the following error message:

2017-05-15 19:34:32,299 - Wavelength. fit_lambda - INFO: gdn4] Writing to: lambda_coeffs_wave_stack_K_m170508_0125-0127.npy
2017-05-15 19:34:32,653 - Wavelength. fit_lambda_helper - INFO: * Fitting Slit gdl2995 from 1907 to 1942
2017-05-15 19:34:32,654 - Wavelength. fit_outwards_refit - INFO: Computing 0 spectrum at 1924
2017-05-15 19:34:32,654 - Wavelength. fit_lambda_helper - INFO: * Fitting Slit GN-z11 from 7 to 82
2017-05-15 19:34:32,654 - Wavelength. fit_lambda_helper - INFO: * Fitting Slit gdl3759 from 1818 to 1853
2017-05-15 19:34:32,655 - Wavelength. fit_lambda_helper - INFO: * Fitting Slit gdl3786 from 1730 to 1765
2017-05-15 19:34:32,655 - Wavelength. fit_outwards_refit - INFO: Computing 0 spectrum at 45
2017-05-15 19:34:32,656 - Wavelength. fit_outwards_refit - INFO: Computing 0 spectrum at 1747
2017-05-15 19:34:32,656 - Wavelength. fit_outwards_refit - INFO: Computing 0 spectrum at 1836
Traceback (most recent call last):
File "Driver.py", line 40, in
Wavelength.fit_lambda(maskname, band, 'Ne.txt', 'Ne.txt',waveops, wavenames2='Ar.txt')
File "/Users/cmc3283/anaconda/lib/python2.7/site-packages/MOSFIRE-1.0.dev0-py2.7.egg/MOSFIRE/Wavelength.py", line 365, in fit_lambda
solutions = p.map(fit_lambda_helper, range(len(bs.ssl)))
File "/Users/cmc3283/anaconda/lib/python2.7/multiprocessing/pool.py", line 252, in map
return self.map_async(func, iterable, chunksize).get()
2017-05-15 19:34:32,660 - Wavelength. fit_lambda_helper - INFO: * Fitting Slit gdl3094 from 1554 to 1634
File "/Users/cmc3283/anaconda/lib/python2.7/multiprocessing/pool.py", line 568, in get
raise self._value
TypeError: slice indices must be integers or None or have an index method
2017-05-15 19:34:32,661 - Wavelength. fit_outwards_refit - INFO: Computing 0 spectrum at 1592
2017-05-15 19:34:32,661 - Wavelength. fit_lambda_helper - INFO: * Fitting Slit gdl3587 from 1464 to 1498
2017-05-15 19:34:32,662 - Wavelength. fit_outwards_refit - INFO: Computing 0 spectrum at 1482

The lambda_coeffs… file is not created, and my impression is that the wavelength solution is just failing to fit across the whole slit, while the interactive portion ran smoothly. I’ve tried to redo the wavelength solution to make sure I didn’t fail to fit any of the slits, but everything looked fine (all slits had good solutions in the interactive sky-based wavelength solution fit). I don’t know if the issue was in trying to merge the wavelength solution from the sky with the arcs?

Is there supposed to be some useful output from the step before to tell whether that ran properly?
Wavelength.apply_interactive(maskname, band, waveops, apply=obsfiles, to='Ar.txt', argon=True)

I get the lambda_center_coeffs_… files for both lamps, and that’s it. It appeared to run without error.

Any ideas y’all might have as a fix would be very useful.

Best,
Caitlin

**Comment by caitlinmcasey** [comment]
Thanks for the reply, Chuck.  I tried that as well, but it didn't seem to work (same error).  Error message is below.  Any other suggestions?

2017-05-17 18:12:42,669 -   Wavelength.          fit_lambda - INFO: gdn4] Writing to: lambda_coeffs_wave_stack_K_m170508_0125-0127.npy
2017-05-17 18:12:42,938 -   Wavelength.   fit_lambda_helper - INFO: * Fitting Slit GN-z11 from 7 to 82
2017-05-17 18:12:42,939 -   Wavelength.  fit_outwards_refit - INFO: Computing 0 spectrum at 45
2017-05-17 18:12:42,939 -   Wavelength.   fit_lambda_helper - INFO: * Fitting Slit gdl2995 from 1907 to 1942
2017-05-17 18:12:42,940 -   Wavelength.  fit_outwards_refit - INFO: Computing 0 spectrum at 1924
2017-05-17 18:12:42,942 -   Wavelength.   fit_lambda_helper - INFO: * Fitting Slit gdl3759 from 1818 to 1853
2017-05-17 18:12:42,943 -   Wavelength.  fit_outwards_refit - INFO: Computing 0 spectrum at 1836
2017-05-17 18:12:42,943 -   Wavelength.   fit_lambda_helper - INFO: * Fitting Slit gdl3786 from 1730 to 1765
2017-05-17 18:12:42,944 -   Wavelength.  fit_outwards_refit - INFO: Computing 0 spectrum at 1747
2017-05-17 18:12:42,946 -   Wavelength.   fit_lambda_helper - INFO: * Fitting Slit gdl3587 from 1464 to 1498
2017-05-17 18:12:42,946 -   Wavelength.   fit_lambda_helper - INFO: * Fitting Slit gdl3094 from 1554 to 1634
Traceback (most recent call last):
  File "Driver.py", line 41, in <module>
2017-05-17 18:12:42,947 -   Wavelength.  fit_outwards_refit - INFO: Computing 0 spectrum at 1482
    Wavelength.fit_lambda(maskname, band, 'Ne.txt', 'Ne.txt',waveops)
  File "/Users/cmc3283/anaconda/lib/python2.7/site-packages/MOSFIRE-1.0.dev0-py2.7.egg/MOSFIRE/Wavelength.py", line 365, in fit_lambda
    solutions = p.map(fit_lambda_helper, range(len(bs.ssl)))
  File "/Users/cmc3283/anaconda/lib/python2.7/multiprocessing/pool.py", line 252, in map
2017-05-17 18:12:42,947 -   Wavelength.  fit_outwards_refit - INFO: Computing 0 spectrum at 1592
    return self.map_async(func, iterable, chunksize).get()
  File "/Users/cmc3283/anaconda/lib/python2.7/multiprocessing/pool.py", line 568, in get
    raise self._value
TypeError: slice indices must be integers or None or have an __index__ method

**Comment by joshwalawender** [comment]
Hi @caitlinmcasey , usually this indicates that the fitting function did not get sufficient data for the fit in either the X or Y axis (or both).  Can you make available a minimum set of files, so I can try to reproduce this behavior here?  That will let me dig in to it.

@csteidel Chuck, I'm going to make the update you suggest to the scripts/AutoDriver.py file.  It looks like this edit will remove all use of the Argon lamp files.  Is that the correct behavior?

**Comment by caitlinmcasey** [comment]
Hi @joshwalawender, I sent you an email to follow up. Thanks for the help!

**Comment by joshwalawender** [comment]
Hi @caitlinmcasey , this is going to be a very unsatisfying answer, but I got the data to process properly on my machine.  

The TypeError that comes out suggests to me that this may be a problem indexing an array.  Can you send me your versions of scipy and numpy?  Here's an example of my output:

```
>>> import numpy
>>> numpy.__version__
'1.11.3'
>>> import scipy
>>> scipy.__version__
'0.18.1'
```

-Josh

**Comment by caitlinmcasey** [comment]
Ha, well that’s reassuring :). The only difference I have is the numpy version:

>>> numpy.__version__
'1.12.1'
>>> import scipy
>>> scipy.__version__
'0.18.1'
>>> 

Now I realize this is probably an important sidenote: I did have to modify Flats.py to get through the flats stage, so perhaps the version of numpy I’m running is a bit more picky?  The issue comes up a few times in Flats.py, where indexing is done with non-integer values.  I modified to round to the nearest integer.  For example in select_roi (line ~378):
v = data[np.int(y-roi_width):np.int(y+roi_width), xp-2:xp+2]

I had to do this several times.  Do you think this could be the issue? I didn’t think it would be at the time because I believe that’s only used to find the initial trace in the center of the mask.

Another thing I just noticed: I have two versions of the mosfire package that installed under the anaconda site-packages directory:
MOSFIRE-1.0.dev-py2.7.egg
MOSFIRE-1.0.dev0-py2.7.egg

It seems I was using the latter to run the reduction.  Perhaps that also has something to do with the issue?

Thanks for your help!
Caitlin

**Comment by followthesheep** [comment]
Hi Caitlin,
I'm not sure if this will help your specific problem, but there are several potential issues with how you're installing the pipeline and conda. The purpose of conda is to isolate your development environment so that each conda environment should have its own version of the packages. For example, I have a conda environment just for running the mosfire pipeline. Using PYTHONPATH overrides the environment isolation mechanism of conda so usually, this should be used sparingly. Pointing PYTHONPATH to directories with packages such as numpy or astropy will cause ALL conda environments to use that version, which will cause a lot of dependency problems. conda actually does not need the PYTHONPATH variable to work (you may still want to use it if you keep all your personal python scripts at the same location). The conda webpage has more some info about this as well: https://conda.io/docs/troubleshooting.html#conda-claims-installed 

I would recommend after you create your conda environment that you switch to it and install numpy and astropy with its specific recommended version for the MOSFIRE pipeline:

`conda install numpy=1.11.3 astropy=1.2.1`

I totally agree that we should add directions for installing the correct package dependency versions on the website.

Tuan

**Comment by caitlinmcasey** [comment]
Hi Tuan,

Thanks for the thoughts.  It makes me think I should back up even further in the story and mention more details about the installation process. Everything I say is from the perspective of a python novice, so I’m sorry if it’s painfully obvious to you that I should have gone about this a different way:
- I originally attempted to use pip to install first numpy, astropy and ccdproc as per the DRP install instructions, rather than using anaconda, but I was unable to make that work due to update issues with numpy.  Basically, I wasn’t able to successfully update the system python numpy beyond 1.7 (I tried using super user, also suspecting that this was an issue related to the brand-new nature of the laptop running Sierra and the fact that my IT department - not in astro - held the laptop hostage for about a month installing all sorts of… things, and likely fiddled with permissions in some way that’s unhelpful).  Because numpy couldn’t update, astropy fails, because it requires a newer version.
- With no luck there, Josh suggested I use the anaconda version, so I downloaded that successfully, though I cannot run any command with ‘conda’ because I always get this error, which is a mystery to me: AttributeError: dlsym(RTLD_DEFAULT, AbsoluteToNanoseconds): symbol not found
- Without success with conda, I simply tried pip install again (with —upgrade for numpy, and then later for astropy), and noticed the updated versions were dumped in the anaconda folders.
- Then I was in a position of running python, and importing numpy, only to find that the PYTHONPATH still pointed to the system python directories (re: numpy version 1.7, so no good), so then I appended the anaconda “site-packages” directory to the PYTHONPATH and everything finally seemed to work.
- From there, I installed mospy and it has mostly worked (with exception of the small edits I had to make to Flats.py) until this point in the wavelength solution.

If y’all think this is rooted in an installation issue, I’d love it if you had advice on how to undo whatever I’ve done and reinstall properly so I don’t run into the same issues.

(I realize the pipeline should also probably work without hacking at the Flats.py stage too, but I was pretty confident I got past that without issues.)

Thanks,
Caitlin


On May 19, 2017, at 12:26 PM, Tuan Do <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi Caitlin,
I'm not sure if this will help your specific problem, but there are several potential issues with how you're installing the pipeline and conda. The purpose of conda is to isolate your development environment so that each conda environment should have its own version of the packages. For example, I have a conda environment just for running the mosfire pipeline. Using PYTHONPATH overrides the environment isolation mechanism of conda so usually, this should be used sparingly. Pointing PYTHONPATH to directories with packages such as numpy or astropy will cause ALL conda environments to use that version, which will cause a lot of dependency problems. conda actually does not need the PYTHONPATH variable to work (you may still want to use it if you keep all your personal python scripts at the same location). The conda webpage has more some info about this as well: https://conda.io/docs/troubleshooting.html#conda-claims-installed

I would recommend after you create your conda environment that you switch to it and install numpy and astropy with its specific recommended version for the MOSFIRE pipeline:

conda install numpy=1.11.3 astropy=1.2.1

I totally agree that we should add directions for installing the correct package dependency versions on the website.

Tuan

**Comment by joshwalawender** [comment]
Hi @caitlinmcasey I think the issue is the indexing with floats as you found in `flats.py`.  *sigh*  I've been trying to go through and squash all the deprecation warnings about indexing with floats when I edit sections of the DRP, but I haven't gone through everything yet (notably `Wavelength.py`).  I think if you back down to numpy v1.11, it will likely work.

The Compatibility Notes in numpy change log suggest that the warning has now been upgraded to a `TypeError` (see [https://docs.scipy.org/doc/numpy/release.html](https://docs.scipy.org/doc/numpy/release.html)) which supports this conclusion.  I'll do some further testing today, but I suspect this is the issue.

**Comment by caitlinmcasey** [comment]
Hi all, thanks!  Reverting to numpy 1.11 solves my problems.  I now get many of the following warnings while generating the wavelength solution:
   using a non-integer number instead of an integer will result in an error in the future
which is exactly what I was running into.  Thanks again to all for your help! Hey, I even learned a little python from this exercise. :)
