### ISSUE TITLE
DRP issue when running test data 

### ISSUE THREAD

**Issue by bnvyed** [Keck-DataReductionPipelines/MosfireDRP#74]
I am new to both python and MOSFIRE, and have data that I am ready to reduce. I have been walking through the DRP step by step with the H-band test data. I have come across a few hiccups that I was able to figure out, but am stuck on my most recent one and hope that someone could help. 

I am on the "wavelength fitting for the entire slit" step and have come across this output:

2017-06-23 11:29:44,510 -   Wavelength.          fit_lambda - INFO: MOSFIRE_DRP_MASK] Writing to: lambda_coeffs_wave_stack_H_m120910_0163-0176.npy
Traceback (most recent call last):
  File "Driver.py", line 36, in <module>
    Wavelength.fit_lambda(maskname, band, obsfiles, obsfiles, waveops)
  File "/Users/bxv3026/Desktop/Research/MosfireDRP-master/DRP_Test_Case_Hband/2012sep10/reduced/MOSFIRE_DRP_MASK/2012sep10/H/MOSFIRE/Wavelength.py", line 364, in fit_lambda
    solutions = p.map(fit_lambda_helper, range(len(bs.ssl)))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/pool.py", line 251, in map
    return self.map_async(func, iterable, chunksize).get()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/pool.py", line 567, in get
    raise self._value
TypeError: 'int' object has no attribute '__getitem__'
2017-06-23 11:29:44,686 -   Wavelength.   fit_lambda_helper - INFO: * Fitting Slit TARG7 from 1952 to 2032
2017-06-23 11:29:44,687 -   Wavelength.  fit_outwards_refit - INFO: Computing 0 spectrum at 1990
/Users/bxv3026/anaconda/lib/python2.7/site-packages/numpy/ma/core.py:3158: VisibleDeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  dout = self.data[indx]
/Users/bxv3026/anaconda/lib/python2.7/site-packages/numpy/ma/core.py:3213: VisibleDeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  dout._mask = _mask[indx]

If needed :
numpy version 1.11.3
astropy version 1.2.1

Any insight is welcome, thank you!

**Comment by MosfireDRP** [comment]
Just to be clear, did you get the warning but the reduction continued or did it stop entirely ?

Anyhow there are posts similar to yours in our repository. It has to do with the fact  that numpy has upgraded a warning to an error when dealing with masked arrays. 

We are working on a fix. 

In the meantime, a possible solution is suggested in the other posts dealing with the same problem and it is to downgrade your version of numpy. 

I am on travel right now but I should be able to help you more when I get to a computer rather than my phone 

Cheers
Luca

**Comment by joshwalawender** [comment]
Hi @bnvyed are you doing an interactive wavelength fit?  If so, this is usually caused by not clicking through all the slits in the MOS mask to form a solution for each.  When you get the wavelength fitting window, hit the `n` key to cycle through all the slits (or hit the `k` key to sigma clip reject wavelength points).  When fit solutions have been completed for all slits, a red "Done!" should appear in the plot window and then you can hit `q` to quite the interactive wavelength solution or just close the graphics window.  I think this will solve your problem, if not, please let me know!

-Josh

**Comment by bnvyed** [comment]
Josh- Thanks that fixed my problem! I must have gotten too excited and only cycled through the first few. 

Brit

**Comment by joshwalawender** [comment]
@bnvyed Great!  Glad that solved it.  I've generated a PR #75 with an edit to the code to put better messaging about this exact issue since I've bumped in to it myself a few times and the reminder will help people who run in to it in the future.
